### ISSUE TITLE
Update and Improve README

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/rinse#28]
- [ ] Add a clear overview of the project and what it does.
- [ ] Add background/philosophy and explain design choices.
- [ ] Improve README structure.
- [ ] Add link to issues.
- [ ] Add badges.

**Comment by grabear** [comment]
Can you make this on a separate "hackseq README" branch?  I'm going to do the same with the renv/beRi.  

This is what Baraa says to do:
>We will have our first day deliverable today: README 1st draft.
> - The draft is due today @ 3PM. It should include description of your project that gives someone outside of your project an idea of what you are doing. If you can include installation requirements and running instructions for the first draft, that is great! If not, that is OK.
> - I would like you to nominate one person from your team to be the Peer Reviewer. Let me know who that is by 3PM, so I would assign them the project which they will review. The review will be due @ 5pm. Bullet points pointing out the things they find confusing, missing, or amazing should be enough

**Comment by sdhutchins** [comment]
Yes, for sure
